---
name: action-download-last-artifact
description: Downloads the last created artifact by name, regardless of which workflow or branch it was created in
inputs: 
  name:
    description: Artifact name
    required: true
  path:
    description: Destination path
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
branding:
  icon: download-cloud
  color: blue
